# Generated by Django 3.2.19 on 2023-07-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0002_auto_20230615_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='toggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=100)),
                ('toggle_value', models.IntegerField(default=0)),
            ],
        ),
    ]
