# Generated by Django 3.2.19 on 2023-07-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0003_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toggle',
            name='toggle_value',
            field=models.BooleanField(default=0),
        ),
    ]
