# Generated by Django 3.2.20 on 2023-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0005_test_custom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
